GET http://localhost:3000/utilizador/list

###
GET http://localhost:3000/utilizador/2/reservas

###
GET http://localhost:3000/utilizador/getUserByToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTU4MjczMjUsImV4cCI6MTY1NTgyNzYyNSwic3ViIjoiMjMifQ.22fDpO3U48hQM9QaoAHARWqJuyE6-hJYyMBAE6XNnJU

###
GET http://localhost:3000/utilizador/3

###
POST http://localhost:3000/utilizador/loginWeb
Content-Type: application/json

{
    "email": "consertino@admin.com",
    "password": "123123"
}

###
POST http://localhost:3000/utilizador/refreshToken
Content-Type: application/json

{
    "env":"web",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsIn5cCI6IkpXVCJ9.eyJpYXQiOjE2NTYxMDAwODksImV4cCI6MTY1NjcwNDg4OSwic3ViIjoiMjYifQ.0x9n_blXlsKTC_hLI5vlBSRJtsUFRciuGfZeOotyohk"
}

###
DELETE  http://localhost:3000/utilizador/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTU5OTU1NDEsImV4cCI6MTY1NjYwMDM0MSwic3ViIjoiMjYifQ.aPkL4l-WCk492GqUdK_4U-Z6nSAmYwOLWHn2221zHkc"
}
