GET http://localhost:3000/utilizador/list

###
GET http://localhost:3000/utilizador/:id/reservas

###
GET http://localhost:3000/utilizador/getUserByToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTU0NzUyNDQsImV4cCI6MTY1NTQ3NTU0NCwic3ViIjoiMTIifQ.NiXKeYzCjKb4d_XYHvWClpl7E97NxW4RB7ZrbmsJgt0

###
GET http://localhost:3000/utilizador/:id

###
POST http://localhost:3000/utilizador/login
Content-Type: application/json

{
    "email": "Consertino@Admin.com",
    "password": "12313"
}

###
POST http://localhost:3000/utilizador/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTU0ODAwNzcsImV4cCI6MTY1NjA4NDg3Nywic3ViIjoiMTQifQ.mytpJUuqcMqMqUdUSGmJ7gRKxP1ujiRFWjAaQrXHpCc"
}

###
DELETE  http://localhost:3000/utilizador/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTU0NzU5MzQsImV4cCI6MTY1NjA4MDczNCwic3ViIjoiMTQifQ.t-rPqAuBt0MaSbbVdpSYvStFdxBV912TV-TO4zU26p0"
}
